### ISSUE TITLE
Minijuegos

### ISSUE THREAD

**Issue by TonyDWKR** [diego-rascon/panther-games#1]
Deberian agregar minijuegos para entretener al usuario mientras llegan clientes. Creo que seria muy bueno, ademas que los juegos sean originales y no descargados de otro lado.

**Comment by diego-rascon** [comment]
¡Gracias por la retroalimentación! hemos tomado en cuenta tu idea y la hemos introducido a nuestro roadmap, actualmente planeamos implementar una inteligencia artificial que desarrolla una versión web de todo juego que es registrado en el inventario, así cuando el usuario se encuentre en la ventana de productos y se encuentra aburrido, solo que tiene que introducir en el teclado "Estoy aburrido, ¿puedo jugar un juego por favor?" y eso mostrará una página en la que se muestran todos los juegos disponibles actualmente, mostrando los trailers de cada uno de ellos en 1440p (tenemos planeado mejorar nuestros servidores para soportar 8K en el futuro). El usuario simplemente hace click en el juego que desea jugar y este se abrirá en ese instante. Recientemente logramos un acuerdo con Nvidia para poder usar parte de los servidores que utilizan para el servicio Geforce Now y decidieron rentarnos 13% de sus equipos a cambio de membresías gratis en Panther Games para toda la mesa de directivos de Nvidia. Planeamos tener esta característica lista para junio y espero que se encuentre tan emocionado como yo sobre el futuro de este punto de venta.

**Comment by TonyDWKR** [comment]
Suena demasiado bien para ser verdad. no puedo esperar a jugar cable HDMI desde la comodidad de mi casa.
